LPS-135072 Accessibility fix, remove IE7 CSS rules starting with *
liferay/alloy-font-awesome pull request #3
Opened 2021-07-02 12:34 UTC by georgel-pop-lr

LPS-135072 Accessibility fix, remove IE7 CSS rules starting with * in Font Awesome

2021-07-06 12:05 UTC, markocikos approved these changes
LGTM!

2021-07-06 13:58 UTC, marcoscv-work commented
LGTM !

2021-07-06 14:02 UTC, edalgrin approved these changes
👏 👏 👏

2021-07-21 15:59 UTC, antonio-ortega commented
Hey guys,

Can we move this forward now?

Thanks.

Regards.

2021-07-22 11:01 UTC, edalgrin commented
Just started reviewing :)

2021-07-22 15:47 UTC, edalgrin requested changes
On a second look, this might need a change, we are changing the source code (*.scss) and I believe we need also the output (*.css)

I'm trying to use the current building/deploying system but it doesn't work due to version/deprecation issues. So we might need to update the dependencies although I think they are most used to build a website we don't really need in our repository. But it's too soon to say it, I'm trying the first solution 👍

2021-07-23 07:36 UTC, georgel-pop-lr commented
> On a second look, this might need a change, we are changing the source code (.scss) and I believe we need also the output (.css)
> 
> I'm trying to use the current building/deploying system but it doesn't work due to version/deprecation issues. So we might need to update the dependencies although I think they are most used to build a website we don't really need in our repository. But it's too soon to say it, I'm trying the first solution

Hi @edalgrin,

We could remove all the rules in less files as well, I don't think will make any harm, but after testing with yarn link on 7.2.x branch it worked only when removing the  (.scss) files in this PR because we use them on https://github.com/liferay/liferay-portal/blob/b795c02a239c901105c23612628a13f0097cab4e/modules/apps/frontend-theme/frontend-theme-font-awesome-web/src/main/resources/META-INF/resources/css/main.scss#L1

Regards.

2021-07-23 10:52 UTC, georgel-pop-lr commented
Hi @edalgrin,

I changed css/font-awesome.css as well and (.less) ones.

Please review.

Thanks.

2021-07-23 16:13 UTC, edalgrin commented
@georgel-pop-lr your I like your solution! I'm going to try it and proceed with the upgrade

2021-07-23 16:14 UTC, edalgrin commented
Just started reviewing :)

2021-07-26 11:19 UTC, edalgrin commented
Resent here https://github.com/liferay/alloy-font-awesome/pull/4

2021-07-26 11:19 UTC, closed without merging